---
- name: Installs nginx web server
  apt: pkg=nginx state=installed

- name: Install supervisord
  apt: pkg=supervisor state=installed

- name: Install git
  apt: pkg=git state=installed

- name: Install node
  apt: pkg=nodejs state=installed

- name: Install node legacy
  apt: pkg=nodejs-legacy state=installed

- name: Install npm
  apt: pkg=npm state=installed

- user: name=whiplash

- name: ssh directory
  file: path=/home/whiplash/.ssh/ state=directory

- name: Authorized keys
  copy: src=../../common/files/authorized_keys dest=/home/whiplash/.ssh/authorized_keys owner=whiplash mode=0600

- name: Create git repository
  command: su whiplash -c 'git init /home/whiplash/whiplash' creates=/home/whiplash/whiplash

- name: Add git hook
  copy: src=post-receive.sh dest=/home/whiplash/whiplash/.git/hooks/post-receive mode=0755 owner=whiplash

- name: Whiplash restart permission
  lineinfile: "dest=/etc/sudoers.d/whiplash owner=root group=root mode=0440
              line='whiplash ALL=(ALL) NOPASSWD: /usr/bin/supervisorctl'
              state=present
              create=yes
              validate='visudo -cf %s'"

- name: Whiplash nginx config
  copy: src=nginx.conf dest=/etc/nginx/sites-enabled/whiplash.conf
  notify:
    - reload nginx

- name: Whiplash supervisord config
  copy: src=whiplash.conf dest=/etc/supervisor/conf.d/whiplash.conf
  notify:
    - restart whiplash

