- name: nginx ssl directory
  file: path=/etc/nginx/ssl state=directory

- name: cpy ssl key
  copy: src=tessel.key dest=/etc/nginx/ssl/tessel_encrypted.key

- name: cpy ssl cert
  copy: src=tessel.pem dest=/etc/nginx/ssl/tessel.pem

- name: decrypt ssl key
  command: openssl rsa -in /etc/nginx/ssl/tessel_encrypted.key -out /etc/nginx/ssl/tessel.key -passin pass:{{ssl_passphrase}} creates=/etc/nginx/ssl/tessel.key

- name: rampart nginx config
  copy: src=nginx.conf dest=/etc/nginx/ssl/tessel.inc
  notify:
    - reload nginx
