---
- name: Installs nginx web server
  apt: pkg=nginx state=installed update_cache=true

- name: Install supervisord
  apt: pkg=supervisor state=installed update_cache=true

- user: name=rampart-bounce generate_ssh_key=yes ssh_key_bits=2048

- name: rampart-bounce supervisord config
  copy: src=rampart-bounce.conf dest=/etc/supervisor/conf.d/rampart-bounce.conf
  notify:
    - restart rampart-bounce

- name: rampart nginx config
  copy: src=nginx.conf dest=/etc/nginx/sites-enabled/rampart.conf
  notify:
    - reload nginx
