- name: ssh directory
  file: path=/root/.ssh/ state=directory

- name: ssh keys
  copy: src=authorized_keys dest=/root/.ssh/authorized_keys mode=644

- name: Disallow SSH password authentication
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^PasswordAuthentication"
    line="PasswordAuthentication no"
    state=present
  notify:
    - restart sshd

- name: install basic utilities
  apt: pkg={{item}} state=present
  with_items:
   - byobu
   - htop

# For DigitalOcean console access. The password is on Mitro.
- name: set root password
  user: name=root password=$6$vr6VYKBSOXpn$6EExGr5Wll3QD3n9yseWjnRFCGbkhgKzDi.IuTyXmpuOq4EmARgYBx3PEwkNfw5zy8VXI9vNMI4Er3vUGLV/w1
