---
- hosts: rampart.tessel.io
  roles:
   - ssl
   - common
   - rampart-master
  vars_prompt:
    - name: ssl_passphrase
      prompt: "Enter SSL Certificate Passphrase"
      private: false

- hosts: rampart.local
  roles:
   - common

- hosts: projects.tessel.io
  roles:
   - common

- hosts: forums.tessel.io
  roles:
   - common

- hosts: shop.tessel.io
  roles:
   - ssl
   - common
   - shop
  vars_prompt:
    - name: ssl_passphrase
      prompt: "Enter SSL Certificate Passphrase"
      private: false

- hosts: auth.tessel.io
  roles:
   - common

- hosts: ops.tessel.io
  roles:
   - ssl
   - common
   - whiplash
  vars_prompt:
    - name: ssl_passphrase
      prompt: "Enter SSL Certificate Passphrase"
      private: false
