---
- name: Installs nginx web server
  apt: pkg=nginx state=installed

- name: Install supervisord
  apt: pkg=supervisor state=installed

- name: Install git
  apt: pkg=git state=installed

- name: Install node
  apt: pkg=nodejs state=installed

- name: Install node legacy
  apt: pkg=nodejs-legacy state=installed

- name: Install npm
  apt: pkg=npm state=installed

- user: name=shop

- name: ssh directory
  file: path=/home/shop/.ssh/ state=directory

- name: Authorized keys
  copy: src=../../common/files/authorized_keys dest=/home/shop/.ssh/authorized_keys owner=shop mode=0600

# - name: Create git repository
#   command: su shop -c 'git init /home/shop/shop' creates=/home/shop/shop

# - name: Add git hook
#   copy: src=post-receive.sh dest=/home/shop/shop/.git/hooks/post-receive mode=0755 owner=shop

- name: shop restart permission
  lineinfile: "dest=/etc/sudoers.d/shop owner=root group=root mode=0440
              line='shop ALL=(ALL) NOPASSWD: /usr/bin/supervisorctl'
              state=present
              create=yes
              validate='visudo -cf %s'"

- name: shop nginx config
  copy: src=nginx.conf dest=/etc/nginx/sites-enabled/shop.conf
  notify:
    - reload nginx

- name: shop supervisord config
  copy: src=shop.conf dest=/etc/supervisor/conf.d/shop.conf
  notify:
    - restart shop
